site_name: MailGun Sender
pages:
  - 'Introduction': 'index.md'
  - 'Plugin API': 'api.md'
  - 'Example': 'example.md'
  - 'About': 'about.md'
copyright: "&copy;2017 C. Byerley - develephant.com"
theme: readthedocs
site_url: https://develephant.github.io/mailgun-sender-plugin
site_dir: ../docs
extra_css: 
  - css/code.css
markdown_extensions:
  - admonition
  - codehilite